name: CDK Deploy

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    if: >
      github.event.issue.pull_request != null &&
      contains(github.event.comment.body, '/cdk-deploy')
    runs-on: ubuntu-latest
    environment:
      name: production # Must match the environment you set up
      # The workflow will pause here until approved

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust as needed

      - name: Install Dependencies
        run: npm install

      - name: Deploy CDK
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: npx cdk deploy --require-approval never

      - name: Merge Pull Request
        uses: peter-evans/merge-pull-request@v4
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: "Merge via GitHub Actions"
          merge-method: squash # Choose between merge, squash, or rebase
