name: CDK Deploy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  cdk_diff:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Run `cdk diff`
        run: |
           cdk diff > diff.txt
           cat diff.txt
      - name: Upload CDK Diff as Artifact
        uses: actions/upload-artifact@v3
        with:
            name: cdk-diff
            path: diff.txt
    
  cdk_deploy:
    needs: cdk_diff
    runs-on: ubuntu-latest 
    permissions: 
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Download CDK Diff Artifact
        uses: actions/download-artifact@v3
        with:
          name: cdk-diff
          path: ./artifacts

      - name: Display CDK Diff
        run: cat ./artifacts/diff.txt  

      - name: Run `cdk deploy`
        run: cdk deploy --require-approval never      

      - name: Configure Git for Automated Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch and Merge Pull Request
        if: success()
        run: |
          # Fetch all branches from the remote
          git fetch origin

          # Checkout to the master branch
          git checkout master

          # Ensure master branch is up-to-date
          git pull origin master

          # Merge the PR branch into master
          git merge ${{ github.event.pull_request.head.ref }} --no-ff -m "Merge PR #${{ github.event.pull_request.number }} via GitHub Actions"

          # Push the merged changes to the remote master branch
          git push origin master
    

