name: CDK Deploy

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created,edited]

jobs:
  cdk_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Run `cdk diff`
        run: |
           cdk diff > diff.txt
           cat diff.txt
        
      - name: Check for Comment Trigger to Deploy
        if: ${{ github.event.comment.body == '/cdk-deploy' }}
        run: echo "Deploy command issued"
   
      - name: Run `cdk deploy` if Approved
        if: ${{ github.event.comment.body == '/cdk-deploy' }}
        run: cdk deploy --require-approval never

      - name: Checkout Master Branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch All Branches
        run: git fetch --all
        
      - name: Checkout Mythili Branch
        run: git checkout -b mythili origin/mythili
      
      - name: Checkout Master Branch
        run: git checkout master
      
      - name: Merge Local `mythili` Branch into Master
        run: git merge mythili --no-edit
      
      - name: Push Merged Changes to Master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin master
        