name: CDK Deploy

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  cdk_diff:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'deploy'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Run `cdk diff`
        run: cdk diff

  approval:
    runs-on: ubuntu-latest
    needs: cdk_diff
    steps:
      - name: Await Manual Approval
        run: echo "Waiting for approval to deploy..."

      # Manual approval step
      - name: Approval Required
        uses: actions/github-script@v6
        with:
          script: |
            const pr_number = context.issue.number;
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: 'Approved for deployment.',
            });

  cdk_deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Run `cdk deploy`
        run: cdk deploy --require-approval never

  merge_pr:
    runs-on: ubuntu-latest
    needs: cdk_deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge the PR if deployment succeeds
        uses: actions/github-script@v6
        with:
          script: |
            const pr_number = context.payload.issue.number;
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
            });
