name: CDK Deploy

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created,edited]

jobs:
  cdk_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Run `cdk diff`
        run: |
           cdk diff > diff.txt
           cat diff.txt
        
      - name: Post diff comment
        uses: actions/github-script@v6
        with:
          script: |
            const comment = `### CDK Diff Results
            \`\`\`
            ${require('fs').readFileSync('diff.txt', 'utf8')}
            \`\`\` Please approve the deployment by commenting \`approve\`.`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Run `cdk deploy`
        run: cdk deploy --require-approval never      

      - name: Merge the PR if deployment succeeds
        run:
          git fetch origin master
          git checkout master
          git merge ${{ github.event.pull_request.head.ref }}
          git push origin master
